### ISSUE TITLE
Consider railroad diagrams in syntax sections to aid understanding

### ISSUE THREAD

**Issue by annevk** [whatwg/url#67]
I've tried to explore railroad diagrams to assist the prose that is already present, but I haven't really figured out how to make them work well without a bunch of surrounding prose. E.g., defining the contents of a host can be done as such:

```
<pre class=railroad>
Choice:
  N: domain
  N: IPv4 address
  Sequence:
    T: [
    N: IPv6 address
    T: ]
</pre>
```

However, it's not clear from this diagram alone that these items together represent a host. The non-terminals can also not contain links.

IPv4 addresses are even harder:

```
<pre class=railroad>
Choice:
  N: 0-9
  Sequence:
    N: 1-9
    N: 0-9
  Sequence:
    T: 1
    N: 0-9
    N: 0-9
  Sequence:
    T: 2
    N: 0-4
    N: 0-9
  Sequence:
    T: 25
    N: 0-5
</pre>

<pre class=railroad>
Sequence:
  N: decimal byte
  T: .
  N: decimal byte
  T: .
  N: decimal byte
  T: .
  N: decimal byte
</pre>
```

It's not clear the first railroad is "decimal byte", it's not clear the second railroad is "IPv4 address", and they don't link to each other.

I think I was hoping for something closer to ABNF, but without the ABNF implications that you can then stick that into some parser generator.
